## Jose V. Die
## April 2017

WBOX=   ['TGACC', 'TGACT'] #Ameline-Torregrosa (2008)
CBF =   ['GTCGAC']         #Ameline-Torregrosa (2008)
DRE =   ['GCCGAC', 'ACCGAC'] #Ameline-Torregrosa (2008)
CAMTA=['ACGCGC', 'ACGCGG', 'ACGCGT', 'CCGCGC', 'CCGCGG', 'CCGCGT', 'GCGCGC', 'GCGCGG', 'GCGCGT']
ABRE=['ACGTGTC']
AtBH5 =['CAATAATTG', 'CAATCATTG', 'CAATTATTG', 'CAATGATTG']
RAV1B=['CACCTG']
AchiVis = ['TGTCA']
AGmotif=['AGATCCAA']
WLE1=['TGACA']
RAV1AAT=['CAACA']
ASF1 = ['TGACG']
nodulin45 =['CTCTT']
DOFCOREZM=['AAAG']
CACTFTPPCA1 =['CACT','TACT']
CAATBOX1=['CCAAT']
GT1CONSENSUS = ['GAAAAA','GATAAA','GAAAAT','GATAAT','GGAAAA','GGAAAT','GGTAAA','GGTAAT']
GTGANTG10=['GTGA']
ARR1AT = ['AGATT','TGATT','CGATT','GGATT']
GATABOX = ['GATA']
POLLEN1LELAT52=['AGAAA']
WRKY71OS=['TGAC']
ROOTMOTIFTAPOX1=['ATATT']
GT1GMSCAM4 = ['GAAAAA']
WBBOXPCWRKY1 =['TTTGACC','TTTGACT']
WBOXATNPR1 =['TTGAC']
WBOXHVISO1 =['TGACT']
WBOXNTCHN48 =['CTGACC','CTGACT']
WBOXNTERF3 =['TGACC','TGACT']
AuxRE1 = ['TGTCTC']                #auxin response element
CATATGGMSAUR = ['CATATG']          #auxin-responsiveness
DRE1COREZMRAB17 = ['ACCGAGA']      #drought
DRE2COREZMRAB17 =['ACCGAC']        #drought
LTRE1HVBLT49 = ['CCGAAA']          # low-temperature-responsive element, cold
LTREATLTI78 = ['ACCGACA']          # low-temperature-responsive element, cold
LTRECOREATCOR15 = ['CCGAC']        # low-temperature-responsive element, cold
MYCATERD1 = ['CATGTG']             # dehydration, water stress
SREATMSD = ['TTATCC']              # sugar-responsive motif
SURE1STPAT21 = ['AATAGAAAA']       # sucrose responsive element (SURE)
SURE2STPAT21 = ['AATACTAAT']       # sucrose Responsive element (SURE2)
IBOXCORENT = ['GATAAGA','GATAAGG'] # light
Gbox =       ['CACATG'] 
MYCATERD22 = ['CACATG']         
GT1GMSCAM4 = ['GAAAAA']        
ERE_GCCbox  = ['AGCCGCC']
ERE_GCCbox  = ['AGCCGCC']
AGCBOXNPGLB = ['AGCCGCC']
GCC_box =     ['GCCGCC'] 



all = [WBOX,CBF, DRE, CAMTA, ABRE, AtBH5,RAV1B, nuevo1, nuevo2, WLE1, RAV1AAT,\
ASF1, nuevo4, DOFCOREZM, CACTFTPPCA1, CAATBOX1, GT1CONSENSUS, GTGANTG10, ARR1AT,\
GATABOX, POLLEN1LELAT52, WRKY71OS, ROOTMOTIFTAPOX1, WBBOXPCWRKY1, \
WBOXATNPR1, WBOXHVISO1, WBOXNTCHN48, WBOXNTERF3, AuxRE1,CATATGGMSAUR, DRE1COREZMRAB17,\
DRE2COREZMRAB17, LTRE1HVBLT49, LTREATLTI78, LTRECOREATCOR15, MYCATERD1, \
SREATMSD,SURE1STPAT21,SURE2STPAT21,IBOXCORENT, MYCATERD22, GT1GMSCAM4, AGCBOXNPGLB]